using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class DirectMessagesUiFragment : BoxContainer
{
    public DirectMessagesUiFragment()
    {
        RobustXamlLoader.Load(this);

    }

}
